# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jimmy/qm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jimmy/qm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jimmy/qm/CMakeFiles /home/jimmy/qm/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jimmy/qm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

include/Monitor.o: include/Monitor.cpp.o

.PHONY : include/Monitor.o

# target to build an object file
include/Monitor.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/Monitor.cpp.o
.PHONY : include/Monitor.cpp.o

include/Monitor.i: include/Monitor.cpp.i

.PHONY : include/Monitor.i

# target to preprocess a source file
include/Monitor.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/Monitor.cpp.i
.PHONY : include/Monitor.cpp.i

include/Monitor.s: include/Monitor.cpp.s

.PHONY : include/Monitor.s

# target to generate assembly for a file
include/Monitor.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/Monitor.cpp.s
.PHONY : include/Monitor.cpp.s

include/Sensors.o: include/Sensors.cpp.o

.PHONY : include/Sensors.o

# target to build an object file
include/Sensors.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/Sensors.cpp.o
.PHONY : include/Sensors.cpp.o

include/Sensors.i: include/Sensors.cpp.i

.PHONY : include/Sensors.i

# target to preprocess a source file
include/Sensors.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/Sensors.cpp.i
.PHONY : include/Sensors.cpp.i

include/Sensors.s: include/Sensors.cpp.s

.PHONY : include/Sensors.s

# target to generate assembly for a file
include/Sensors.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/Sensors.cpp.s
.PHONY : include/Sensors.cpp.s

include/bsp.o: include/bsp.cpp.o

.PHONY : include/bsp.o

# target to build an object file
include/bsp.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/bsp.cpp.o
.PHONY : include/bsp.cpp.o

include/bsp.i: include/bsp.cpp.i

.PHONY : include/bsp.i

# target to preprocess a source file
include/bsp.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/bsp.cpp.i
.PHONY : include/bsp.cpp.i

include/bsp.s: include/bsp.cpp.s

.PHONY : include/bsp.s

# target to generate assembly for a file
include/bsp.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/bsp.cpp.s
.PHONY : include/bsp.cpp.s

include/qstamp.o: include/qstamp.cpp.o

.PHONY : include/qstamp.o

# target to build an object file
include/qstamp.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/qstamp.cpp.o
.PHONY : include/qstamp.cpp.o

include/qstamp.i: include/qstamp.cpp.i

.PHONY : include/qstamp.i

# target to preprocess a source file
include/qstamp.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/qstamp.cpp.i
.PHONY : include/qstamp.cpp.i

include/qstamp.s: include/qstamp.cpp.s

.PHONY : include/qstamp.s

# target to generate assembly for a file
include/qstamp.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/include/qstamp.cpp.s
.PHONY : include/qstamp.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

qf/qep_hsm.o: qf/qep_hsm.cpp.o

.PHONY : qf/qep_hsm.o

# target to build an object file
qf/qep_hsm.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qep_hsm.cpp.o
.PHONY : qf/qep_hsm.cpp.o

qf/qep_hsm.i: qf/qep_hsm.cpp.i

.PHONY : qf/qep_hsm.i

# target to preprocess a source file
qf/qep_hsm.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qep_hsm.cpp.i
.PHONY : qf/qep_hsm.cpp.i

qf/qep_hsm.s: qf/qep_hsm.cpp.s

.PHONY : qf/qep_hsm.s

# target to generate assembly for a file
qf/qep_hsm.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qep_hsm.cpp.s
.PHONY : qf/qep_hsm.cpp.s

qf/qep_msm.o: qf/qep_msm.cpp.o

.PHONY : qf/qep_msm.o

# target to build an object file
qf/qep_msm.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qep_msm.cpp.o
.PHONY : qf/qep_msm.cpp.o

qf/qep_msm.i: qf/qep_msm.cpp.i

.PHONY : qf/qep_msm.i

# target to preprocess a source file
qf/qep_msm.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qep_msm.cpp.i
.PHONY : qf/qep_msm.cpp.i

qf/qep_msm.s: qf/qep_msm.cpp.s

.PHONY : qf/qep_msm.s

# target to generate assembly for a file
qf/qep_msm.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qep_msm.cpp.s
.PHONY : qf/qep_msm.cpp.s

qf/qf_act.o: qf/qf_act.cpp.o

.PHONY : qf/qf_act.o

# target to build an object file
qf/qf_act.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_act.cpp.o
.PHONY : qf/qf_act.cpp.o

qf/qf_act.i: qf/qf_act.cpp.i

.PHONY : qf/qf_act.i

# target to preprocess a source file
qf/qf_act.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_act.cpp.i
.PHONY : qf/qf_act.cpp.i

qf/qf_act.s: qf/qf_act.cpp.s

.PHONY : qf/qf_act.s

# target to generate assembly for a file
qf/qf_act.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_act.cpp.s
.PHONY : qf/qf_act.cpp.s

qf/qf_actq.o: qf/qf_actq.cpp.o

.PHONY : qf/qf_actq.o

# target to build an object file
qf/qf_actq.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_actq.cpp.o
.PHONY : qf/qf_actq.cpp.o

qf/qf_actq.i: qf/qf_actq.cpp.i

.PHONY : qf/qf_actq.i

# target to preprocess a source file
qf/qf_actq.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_actq.cpp.i
.PHONY : qf/qf_actq.cpp.i

qf/qf_actq.s: qf/qf_actq.cpp.s

.PHONY : qf/qf_actq.s

# target to generate assembly for a file
qf/qf_actq.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_actq.cpp.s
.PHONY : qf/qf_actq.cpp.s

qf/qf_defer.o: qf/qf_defer.cpp.o

.PHONY : qf/qf_defer.o

# target to build an object file
qf/qf_defer.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_defer.cpp.o
.PHONY : qf/qf_defer.cpp.o

qf/qf_defer.i: qf/qf_defer.cpp.i

.PHONY : qf/qf_defer.i

# target to preprocess a source file
qf/qf_defer.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_defer.cpp.i
.PHONY : qf/qf_defer.cpp.i

qf/qf_defer.s: qf/qf_defer.cpp.s

.PHONY : qf/qf_defer.s

# target to generate assembly for a file
qf/qf_defer.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_defer.cpp.s
.PHONY : qf/qf_defer.cpp.s

qf/qf_dyn.o: qf/qf_dyn.cpp.o

.PHONY : qf/qf_dyn.o

# target to build an object file
qf/qf_dyn.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_dyn.cpp.o
.PHONY : qf/qf_dyn.cpp.o

qf/qf_dyn.i: qf/qf_dyn.cpp.i

.PHONY : qf/qf_dyn.i

# target to preprocess a source file
qf/qf_dyn.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_dyn.cpp.i
.PHONY : qf/qf_dyn.cpp.i

qf/qf_dyn.s: qf/qf_dyn.cpp.s

.PHONY : qf/qf_dyn.s

# target to generate assembly for a file
qf/qf_dyn.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_dyn.cpp.s
.PHONY : qf/qf_dyn.cpp.s

qf/qf_mem.o: qf/qf_mem.cpp.o

.PHONY : qf/qf_mem.o

# target to build an object file
qf/qf_mem.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_mem.cpp.o
.PHONY : qf/qf_mem.cpp.o

qf/qf_mem.i: qf/qf_mem.cpp.i

.PHONY : qf/qf_mem.i

# target to preprocess a source file
qf/qf_mem.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_mem.cpp.i
.PHONY : qf/qf_mem.cpp.i

qf/qf_mem.s: qf/qf_mem.cpp.s

.PHONY : qf/qf_mem.s

# target to generate assembly for a file
qf/qf_mem.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_mem.cpp.s
.PHONY : qf/qf_mem.cpp.s

qf/qf_port.o: qf/qf_port.cpp.o

.PHONY : qf/qf_port.o

# target to build an object file
qf/qf_port.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_port.cpp.o
.PHONY : qf/qf_port.cpp.o

qf/qf_port.i: qf/qf_port.cpp.i

.PHONY : qf/qf_port.i

# target to preprocess a source file
qf/qf_port.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_port.cpp.i
.PHONY : qf/qf_port.cpp.i

qf/qf_port.s: qf/qf_port.cpp.s

.PHONY : qf/qf_port.s

# target to generate assembly for a file
qf/qf_port.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_port.cpp.s
.PHONY : qf/qf_port.cpp.s

qf/qf_ps.o: qf/qf_ps.cpp.o

.PHONY : qf/qf_ps.o

# target to build an object file
qf/qf_ps.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_ps.cpp.o
.PHONY : qf/qf_ps.cpp.o

qf/qf_ps.i: qf/qf_ps.cpp.i

.PHONY : qf/qf_ps.i

# target to preprocess a source file
qf/qf_ps.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_ps.cpp.i
.PHONY : qf/qf_ps.cpp.i

qf/qf_ps.s: qf/qf_ps.cpp.s

.PHONY : qf/qf_ps.s

# target to generate assembly for a file
qf/qf_ps.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_ps.cpp.s
.PHONY : qf/qf_ps.cpp.s

qf/qf_qact.o: qf/qf_qact.cpp.o

.PHONY : qf/qf_qact.o

# target to build an object file
qf/qf_qact.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_qact.cpp.o
.PHONY : qf/qf_qact.cpp.o

qf/qf_qact.i: qf/qf_qact.cpp.i

.PHONY : qf/qf_qact.i

# target to preprocess a source file
qf/qf_qact.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_qact.cpp.i
.PHONY : qf/qf_qact.cpp.i

qf/qf_qact.s: qf/qf_qact.cpp.s

.PHONY : qf/qf_qact.s

# target to generate assembly for a file
qf/qf_qact.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_qact.cpp.s
.PHONY : qf/qf_qact.cpp.s

qf/qf_qeq.o: qf/qf_qeq.cpp.o

.PHONY : qf/qf_qeq.o

# target to build an object file
qf/qf_qeq.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_qeq.cpp.o
.PHONY : qf/qf_qeq.cpp.o

qf/qf_qeq.i: qf/qf_qeq.cpp.i

.PHONY : qf/qf_qeq.i

# target to preprocess a source file
qf/qf_qeq.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_qeq.cpp.i
.PHONY : qf/qf_qeq.cpp.i

qf/qf_qeq.s: qf/qf_qeq.cpp.s

.PHONY : qf/qf_qeq.s

# target to generate assembly for a file
qf/qf_qeq.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_qeq.cpp.s
.PHONY : qf/qf_qeq.cpp.s

qf/qf_qmact.o: qf/qf_qmact.cpp.o

.PHONY : qf/qf_qmact.o

# target to build an object file
qf/qf_qmact.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_qmact.cpp.o
.PHONY : qf/qf_qmact.cpp.o

qf/qf_qmact.i: qf/qf_qmact.cpp.i

.PHONY : qf/qf_qmact.i

# target to preprocess a source file
qf/qf_qmact.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_qmact.cpp.i
.PHONY : qf/qf_qmact.cpp.i

qf/qf_qmact.s: qf/qf_qmact.cpp.s

.PHONY : qf/qf_qmact.s

# target to generate assembly for a file
qf/qf_qmact.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_qmact.cpp.s
.PHONY : qf/qf_qmact.cpp.s

qf/qf_time.o: qf/qf_time.cpp.o

.PHONY : qf/qf_time.o

# target to build an object file
qf/qf_time.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_time.cpp.o
.PHONY : qf/qf_time.cpp.o

qf/qf_time.i: qf/qf_time.cpp.i

.PHONY : qf/qf_time.i

# target to preprocess a source file
qf/qf_time.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_time.cpp.i
.PHONY : qf/qf_time.cpp.i

qf/qf_time.s: qf/qf_time.cpp.s

.PHONY : qf/qf_time.s

# target to generate assembly for a file
qf/qf_time.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/qf/qf_time.cpp.s
.PHONY : qf/qf_time.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... edit_cache"
	@echo "... include/Monitor.o"
	@echo "... include/Monitor.i"
	@echo "... include/Monitor.s"
	@echo "... include/Sensors.o"
	@echo "... include/Sensors.i"
	@echo "... include/Sensors.s"
	@echo "... include/bsp.o"
	@echo "... include/bsp.i"
	@echo "... include/bsp.s"
	@echo "... include/qstamp.o"
	@echo "... include/qstamp.i"
	@echo "... include/qstamp.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... qf/qep_hsm.o"
	@echo "... qf/qep_hsm.i"
	@echo "... qf/qep_hsm.s"
	@echo "... qf/qep_msm.o"
	@echo "... qf/qep_msm.i"
	@echo "... qf/qep_msm.s"
	@echo "... qf/qf_act.o"
	@echo "... qf/qf_act.i"
	@echo "... qf/qf_act.s"
	@echo "... qf/qf_actq.o"
	@echo "... qf/qf_actq.i"
	@echo "... qf/qf_actq.s"
	@echo "... qf/qf_defer.o"
	@echo "... qf/qf_defer.i"
	@echo "... qf/qf_defer.s"
	@echo "... qf/qf_dyn.o"
	@echo "... qf/qf_dyn.i"
	@echo "... qf/qf_dyn.s"
	@echo "... qf/qf_mem.o"
	@echo "... qf/qf_mem.i"
	@echo "... qf/qf_mem.s"
	@echo "... qf/qf_port.o"
	@echo "... qf/qf_port.i"
	@echo "... qf/qf_port.s"
	@echo "... qf/qf_ps.o"
	@echo "... qf/qf_ps.i"
	@echo "... qf/qf_ps.s"
	@echo "... qf/qf_qact.o"
	@echo "... qf/qf_qact.i"
	@echo "... qf/qf_qact.s"
	@echo "... qf/qf_qeq.o"
	@echo "... qf/qf_qeq.i"
	@echo "... qf/qf_qeq.s"
	@echo "... qf/qf_qmact.o"
	@echo "... qf/qf_qmact.i"
	@echo "... qf/qf_qmact.s"
	@echo "... qf/qf_time.o"
	@echo "... qf/qf_time.i"
	@echo "... qf/qf_time.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

