//$file${./include::Sensors.cpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: model.qm
// File:  ${./include::Sensors.cpp}
//
// This code has been generated by QM 5.2.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${./include::Sensors.cpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpcpp.hpp"  // QP/C++ framework API
#include "bsp.h"    // Board Support Package interface
#include <iostream>   // for cout/cerr
#include <cstdlib>    // for exit()
#include <chrono>
#include "Sensors.h"

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpcpp version 6.9.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${AOs::Sensors_ptr} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Sensors_ptr} ........................................................
QP::QActive * const Sensors_ptr = &Sensors::instance;
//$enddef${AOs::Sensors_ptr} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::Sensors} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Sensors} ............................................................
Sensors Sensors::instance;

//${AOs::Sensors::Sensors} ...................................................
Sensors::Sensors()
  : QActive(Q_STATE_CAST(&Sensors::initial)),
    tim(this, TIMEOUT_SIG, 0U)
{}

//${AOs::Sensors::SM} ........................................................
Q_STATE_DEF(Sensors, initial) {
    //${AOs::Sensors::SM::initial}
    tim.armX(100,100);

    QS_FUN_DICTIONARY(&Sensors::GetData1);
    QS_FUN_DICTIONARY(&Sensors::GetData2);

    return tran(&GetData1);
}

//${AOs::Sensors::SM::GetData1} ..............................................
Q_STATE_DEF(Sensors, GetData1) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Sensors::SM::GetData1}
        case Q_ENTRY_SIG: {
            std::cout<<"Hi"<<std::endl;
            instance.evt={NEXT_SIG};
            Sensors_ptr->postLIFO(&instance.evt);
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::Sensors::SM::GetData1::NEXT}
        case NEXT_SIG: {
            status_ = tran(&GetData2);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}

//${AOs::Sensors::SM::GetData2} ..............................................
Q_STATE_DEF(Sensors, GetData2) {
    QP::QState status_;
    switch (e->sig) {
        //${AOs::Sensors::SM::GetData2}
        case Q_ENTRY_SIG: {
            std::cout<<"Halo"<<std::endl;
            status_ = Q_RET_HANDLED;
            break;
        }
        //${AOs::Sensors::SM::GetData2::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = tran(&GetData1);
            break;
        }
        default: {
            status_ = super(&top);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::Sensors} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
